#!/bin/sh

#
# install.sh
#
# To use this script, ensure that no instance of aipm is installed, and if
# there was one installed in the past, make sure all traces of it have been
# removed. After this, cd into the directory that this file is contained in,
# then run this file with `sh ./install.sh`.
#
# Author: Logan Savage
# Version 0.2.2
# Date: 2022-03-08
# Copyright (c) 2022 Logan Savage. Some Rights Reserved. See LICENSE.
#

_aipm_init="#!/bin/sh
# The following lines are generated by AIPM; do not modify them,
# or you risk damaging the functionality of the program."

echo "Installing aipm to ~/.local/aipm/aipm; aliasing as aipm"

if [ ! -d src ]; then
    echo "Make sure that you are cd'd into the aipm directory"
    exit
fi

if [ ! -d ~/.local ]; then mkdir ~/.local; fi

if [ ! -d ~/.local/aipm ]; then mkdir ~/.local/aipm; fi
if [ ! -d ~/.local/aipm/bin ]; then mkdir ~/.local/aipm/bin; fi

#cd $(dirname "${BASH_SOURCE[0]}")
make
cp ./bin/aipm ~/.local/aipm/aipm

echo "$_aipm_init" > ~/.aipm_aliases.sh

echo "\nsource ~/.aipm_aliases.sh\nalias aipm=\"~/.local/aipm/aipm\"\n" >> ~/.bashrc
echo "\nsource ~/.aipm_aliases.sh\nalias aipm=\"~/.local/aipm/aipm\"\n" >> ~/.zshrc

source ~/.aipm_aliases.sh

echo "Done!"
